-- MySQL Script generated by MySQL Workbench
-- jue 05 feb 2026 09:58:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoTecnoStore_S1Java_MartinezVillamizarStiven
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoTecnoStore_S1Java_MartinezVillamizarStiven
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven` ;
USE `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven` ;

-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`GestiónCelulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`GestiónCelulares` (
  `idGestiónCelulares` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `precio` DECIMAL NULL,
  `stock` VARCHAR(45) NULL,
  `sistema operativo` VARCHAR(45) NULL,
  `gama` DECIMAL NULL,
  PRIMARY KEY (`idGestiónCelulares`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`GestionClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`GestionClientes` (
  `idGestionClientes` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `identificación` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`idGestionClientes`, `telefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`GestiónVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`GestiónVentas` (
  `idGestiónVentas` INT NOT NULL,
  PRIMARY KEY (`idGestiónVentas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`marca` (
  `idmarca` INT NOT NULL,
  `idcelular` VARCHAR(45) NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`Celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`Celular` (
  `idCelular` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `idmarca` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `marca_idmarca` INT NOT NULL,
  PRIMARY KEY (`idCelular`),
  INDEX `fk_Celular_marca_idx` (`marca_idmarca` ASC) VISIBLE,
  CONSTRAINT `fk_Celular_marca`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`Clientes` (
  `idClientes` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `identificacion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `Celular_idCelular` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Celular1_idx` (`Celular_idCelular` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Celular1`
    FOREIGN KEY (`Celular_idCelular`)
    REFERENCES `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`Celular` (`idCelular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`Ventas` (
  `idVentas` INT NOT NULL,
  `idclientes` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  PRIMARY KEY (`idVentas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoTecnoStore_S1Java_MartinezVillamizarStiven`.`detalle_ventas` (
  `iddetalle_ventas` INT NOT NULL,
  `idVentas` VARCHAR(45) NULL,
  `idcelular` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `subtotal` VARCHAR(45) NULL,
  PRIMARY KEY (`iddetalle_ventas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
